apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: app
        image: 322218137685.dkr.ecr.us-west-2.amazonaws.com/flaskapp:latest
        ports:
          - containerPort: 5000